/*
 * reset_counter.h
 *
 *  Created on: 2022/04/15
 *      Author: SAT37
 */

#ifndef SRC_USER_DRIVERS_CDH_RESET_COUNTER_H_
#define SRC_USER_DRIVERS_CDH_RESET_COUNTER_H_

typedef enum
{
    RESET_CAUSE_UNKNOWN = 0,
    RESET_CAUSE_LOW_POWER_RESET,
    RESET_CAUSE_WINDOW_WATCHDOG_RESET,
    RESET_CAUSE_INDEPENDENT_WATCHDOG_RESET,
    RESET_CAUSE_SOFTWARE_RESET,
    RESET_CAUSE_POWER_ON_POWER_DOWN_RESET,
    RESET_CAUSE_EXTERNAL_RESET_PIN_RESET,
    RESET_CAUSE_BROWNOUT_RESET,
	TOTAL_RESET
} reset_cause_t;

reset_cause_t reset_cause_get(void);



#endif /* SRC_USER_DRIVERS_CDH_RESET_COUNTER_H_ */
