################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
C_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
1U_config/Drivers/STM32F4xx_HAL_Driver/Src \
1U_config/Src \
Startup \
src/src_core/Applications/TestApp \
src/src_core/Applications \
src/src_core/Drivers/Protocol \
src/src_core/Drivers/Super \
src/src_core/IfWrapper/Common \
src/src_core/Library \
src/src_core/Library/libc \
src/src_core/System/ApplicationManager \
src/src_core/System/EventManager \
src/src_core/System/ModeManager \
src/src_core/System/TaskManager \
src/src_core/System/TimeManager \
src/src_core/System/WatchdogTimer \
src/src_core/TlmCmd/Ccsds \
src/src_core/TlmCmd \
src/src_core \
src/src_user/Applications/DriverInstances \
src/src_user/Applications/Middleware \
src/src_user/Applications/UserDefined/Aocs/ACS \
src/src_user/Applications/UserDefined/Aocs/ADS \
src/src_user/Applications/UserDefined/Aocs \
src/src_user/Applications/UserDefined/Aocs/OCS \
src/src_user/Applications/UserDefined/Aocs/ODS \
src/src_user/Applications/UserDefined/Cdh \
src/src_user/Applications/UserDefined/Cdh/Repro \
src/src_user/Applications/UserDefined/Com \
src/src_user/Applications/UserDefined \
src/src_user/Applications/UserDefined/Memory \
src/src_user/Applications/UserDefined/Mission \
src/src_user/Applications/UserDefined/Power \
src/src_user/Applications/UserDefined/Sensor \
src/src_user/Applications \
src/src_user/Drivers/Aocs \
src/src_user/Drivers/Aocs/LinearAlgebra \
src/src_user/Drivers/Cdh \
src/src_user/Drivers/Cdh/EEPROM \
src/src_user/Drivers/Cdh/Flash \
src/src_user/Drivers/Cdh/LoRa \
src/src_user/Drivers/Cdh/MRAM \
src/src_user/Drivers/Cdh/RTC \
src/src_user/Drivers/Cdh/SD \
src/src_user/Drivers/Cdh/SPIPROM \
src/src_user/Drivers/Cdh/WDT \
src/src_user/Drivers/Com/COBC \
src/src_user/Drivers/Com \
src/src_user/Drivers/Com/GS \
src/src_user/Drivers/Com/INTER_SAT \
src/src_user/Drivers/Com/RXPIC \
src/src_user/Drivers/Com/SOBC \
src/src_user/Drivers/Com/TXPIC \
src/src_user/Drivers/Dbg \
src/src_user/Drivers/Etc \
src/src_user/Drivers/Power \
src/src_user/Drivers/Sensor \
src/src_user/Drivers \
src/src_user/IfWrapper \
src/src_user/IfWrapper/SilsMockup \
src/src_user/Library \
src/src_user/Library/General \
src/src_user/Library/SDcard \
src/src_user/ReProgramming/Command \
src/src_user/Settings/Modes/Eqlipse \
src/src_user/Settings/Modes/Phase \
src/src_user/Settings/Modes/TaskLists \
src/src_user/Settings/Modes/TaskLists/Elements \
src/src_user/Settings/Modes/Transitions \
src/src_user/Settings/Modes \
src/src_user/Settings/System/EventHandlerRules \
src/src_user/Settings/System \
src/src_user/Settings/TlmCmd/Ccsds \
src/src_user/Settings/TlmCmd \
src/src_user/TlmCmd/Ccsds \
src/src_user/TlmCmd/NormalBlockCommandDefinition \
src/src_user/TlmCmd \
src/src_user \

