/**
 * @file
 * @brief モード定義とモード遷移定義
 */
#ifndef MODE_DEFINITIONS_H_
#define MODE_DEFINITIONS_H_

typedef enum
{
  MD_AOCSFLAG_START_UP          = 0,          //  0: 起動直後
  MD_AOCSFLAG_STANDBY,
  MD_AOCSFLAG_MISSION_STANDBY,
  MD_AOCSFLAG_DAMPING,
  MD_AOCSFLAG_SUN_POINTING,
  MD_AOCSFLAG_EARTH_CENTER_POINTING,
  MD_AOCSFLAG_GROUND_TRACKING,
  MD_AOCSFLAG_INERTIAL_POINTING,
  MD_AOCSFLAG_VELOCITY_DIRECTION_POINTING,
  MD_AOCSFLAG_HIGH_RATE_SPIN,
  MD_AOCSFLAG_OTHER_SATELLITE_POINTING,
  MD_AOCSFLAG_RELATIVE_ORBITAL_CONTROL,
  MD_AOCSFLAG_CHECK_OUT,
  MD_AOCSFLAG_RESERVED_1,         // 13: 自由に使用できるフラグ1
  MD_AOCSFLAG_RESERVED_2,         // 14: 自由に使用できるフラグ2
  MD_AOCSFLAG_RESERVED_3,         // 15: 自由に使用できるフラグ3
  MD_AOCSFLAG_RESERVED_4,         // 16: 自由に使用できるフラグ4
  MD_AOCSFLAG_DBG,				  // 17: 全フラグを上げる
  MD_AOCSFLAG_MAX
} MD_AOCSMODEID;

typedef enum
{
  MD_MODEID_START_UP          = 0,          //  0: 起動直後
  MD_MODEID_STANDBY,
  MD_MODEID_MISSION_STANDBY,
  MD_MODEID_DAMPING,
  MD_MODEID_SUN_POINTING,
  MD_MODEID_EARTH_CENTER_POINTING,
  MD_MODEID_GROUND_TRACKING,
  MD_MODEID_INERTIAL_POINTING,
  MD_MODEID_VELOCITY_DIRECTION_POINTING,
  MD_MODEID_HIGH_RATE_SPIN,
  MD_MODEID_OTHER_SATELLITE_POINTING,
  MD_MODEID_RELATIVE_ORBITAL_CONTROL,
  MD_MODEID_CHECK_OUT,
  MD_MODEID_RESERVED1,
  MD_MODEID_RESERVED2,
  MD_MODEID_RESERVED3,
  MD_MODEID_RESERVED4,
  MD_MODEID_DBG,
  MD_MODEID_MODE_MAX
} MD_MODEID;

void MD_load_mode_list(void);
void MD_load_transition_table(void);

#endif
